<?php

namespace ContainerWHyK5EX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncuentraControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EncuentraController' shared autowired service.
     *
     * @return \App\Controller\EncuentraController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EncuentraController.php';

        $container->services['App\\Controller\\EncuentraController'] = $instance = new \App\Controller\EncuentraController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\EncuentraController', $container));

        return $instance;
    }
}
