<?php

namespace ContainerTvzXrph;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__G5p2MpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..g5p2Mp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..g5p2Mp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\ReservaController::delete' => ['privates', '.service_locator.wg00WGm', 'get_ServiceLocator_Wg00WGmService', true],
            'App\\Controller\\ReservaController::edit' => ['privates', '.service_locator.wg00WGm', 'get_ServiceLocator_Wg00WGmService', true],
            'App\\Controller\\ReservaController::index' => ['privates', '.service_locator.atZY5CF', 'get_ServiceLocator_AtZY5CFService', true],
            'App\\Controller\\ReservaController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ReservaController::show' => ['privates', '.service_locator.3DipYnt', 'get_ServiceLocator_3DipYntService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController::delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController::edit' => ['privates', '.service_locator.3F8krw9', 'get_ServiceLocator_3F8krw9Service', true],
            'App\\Controller\\UserController::edit2' => ['privates', '.service_locator.3F8krw9', 'get_ServiceLocator_3F8krw9Service', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController::show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.jpvOrpT', 'get_ServiceLocator_JpvOrpTService', true],
            'App\\Controller\\ReservaController:delete' => ['privates', '.service_locator.wg00WGm', 'get_ServiceLocator_Wg00WGmService', true],
            'App\\Controller\\ReservaController:edit' => ['privates', '.service_locator.wg00WGm', 'get_ServiceLocator_Wg00WGmService', true],
            'App\\Controller\\ReservaController:index' => ['privates', '.service_locator.atZY5CF', 'get_ServiceLocator_AtZY5CFService', true],
            'App\\Controller\\ReservaController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ReservaController:show' => ['privates', '.service_locator.3DipYnt', 'get_ServiceLocator_3DipYntService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\UserController:delete' => ['privates', '.service_locator.rvMNZGh', 'get_ServiceLocator_RvMNZGhService', true],
            'App\\Controller\\UserController:edit' => ['privates', '.service_locator.3F8krw9', 'get_ServiceLocator_3F8krw9Service', true],
            'App\\Controller\\UserController:edit2' => ['privates', '.service_locator.3F8krw9', 'get_ServiceLocator_3F8krw9Service', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.kPUOGb8', 'get_ServiceLocator_KPUOGb8Service', true],
            'App\\Controller\\UserController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\UserController:show' => ['privates', '.service_locator.Hz5btge', 'get_ServiceLocator_Hz5btgeService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ReservaController::delete' => '?',
            'App\\Controller\\ReservaController::edit' => '?',
            'App\\Controller\\ReservaController::index' => '?',
            'App\\Controller\\ReservaController::new' => '?',
            'App\\Controller\\ReservaController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::delete' => '?',
            'App\\Controller\\UserController::edit' => '?',
            'App\\Controller\\UserController::edit2' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::new' => '?',
            'App\\Controller\\UserController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ReservaController:delete' => '?',
            'App\\Controller\\ReservaController:edit' => '?',
            'App\\Controller\\ReservaController:index' => '?',
            'App\\Controller\\ReservaController:new' => '?',
            'App\\Controller\\ReservaController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:delete' => '?',
            'App\\Controller\\UserController:edit' => '?',
            'App\\Controller\\UserController:edit2' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:new' => '?',
            'App\\Controller\\UserController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
