<?php

namespace ContainerTvzXrph;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wg00WGmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wg00WGm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wg00WGm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'reserva' => ['privates', 'App\\Entity\\Reserva', 'getReservaService', true],
        ], [
            'entityManager' => '?',
            'reserva' => 'App\\Entity\\Reserva',
        ]);
    }
}
