<?php

namespace ContainerTvzXrph;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservaTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ReservaType' shared autowired service.
     *
     * @return \App\Form\ReservaType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ReservaType.php';

        return $container->privates['App\\Form\\ReservaType'] = new \App\Form\ReservaType();
    }
}
