<?php

namespace ContainerTvzXrph;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Entity\Reserva' shared autowired service.
     *
     * @return \App\Entity\Reserva
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Entity/Reserva.php';

        return $container->privates['App\\Entity\\Reserva'] = new \App\Entity\Reserva();
    }
}
